package automod_legacy

// This list is in alphabethical order
// Open a pr or bug me on discord if you want a word added
var BuiltinSwearWords = map[string]bool{
	"ballsack":    true,
	"bastard":     true,
	"bollock":     true,
	"bollok":      true,
	"cum":         true,
	"cunt":        true,
	"fag":         true,
	"faggot":      true,
	"feck":        true,
	"fellate":     true,
	"fellatio":    true,
	"felching":    true,
	"fudgepacker": true,
	"jerk":        true,
	"knobend":     true,
	"labia":       true,
	"muff":        true,
	"nigger":      true,
	"nigga":       true,
	"pussy":       true,
	"queer":       true,
	"scrotum":     true,
	"sh1t":        true,
	"smegma":      true,
	"spunk":       true,
	"tranny":       true,
	"trannies":     true,
	"tosser":      true,
	"turd":        true,
	"twat":        true,
	"wank":        true,
	"whore":       true,
	"asshole":     true,
	"fvck":        true,
	"asshat":      true,
	"pu55y":       true,
}
